
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mydemo
  name: mydemo
spec:
  type: NodePort
  selector:
    app: mydemo
  ports:
  - name: mydemo
    protocol: TCP
    port: 4986
    
    targetPort: 4986
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemo
spec:
  selector:
    matchLabels:
      app: mydemo
  replicas: 1
  template:
    metadata:
      labels:
        app: mydemo
    spec:
      containers:
        - name: mydemo
          image: okn77/mydemo:v1
          imagePullPolicy: "Always"